package enums;

/**
 * @author Kaelan
 */
enum abstract SpriteIndexOne(Int) from Int to Int
{
	//Rely on implicit casting to get the values of these
	var PLAYER_MALE_FORWARD_TL:Int;
	var PLAYER_MALE_FORWARD_TR:Int;
	var PLAYER_MALE_FORWARD_BL:Int;
	var PLAYER_MALE_FORWARD_BR:Int;
	
	var PLAYER_MALE_BACKWARD_TL:Int;
	var PLAYER_MALE_BACKWARD_TR:Int;
	var PLAYER_MALE_BACKWARD_BL:Int;
	var PLAYER_MALE_BACKWARD_BR:Int;
	
	var PLAYER_MALE_SIDE_TL:Int;
	var PLAYER_MALE_SIDE_TR:Int;
	var PLAYER_MALE_SIDE_BL:Int;
	var PLAYER_MALE_SIDE_BR:Int;
	
	var PLAYER_MALE_FORWARD_WALK_TL:Int;
	var PLAYER_MALE_FORWARD_WALK_TR:Int;
	var PLAYER_MALE_FORWARD_WALK_BL:Int;
	var PLAYER_MALE_FORWARD_WALK_BR:Int;
	
	var PLAYER_MALE_BACKWARD_WALK_TL:Int;
	var PLAYER_MALE_BACKWARD_WALK_TR:Int;
	var PLAYER_MALE_BACKWARD_WALK_BL:Int;
	var PLAYER_MALE_BACKWARD_WALK_BR:Int;
	
	var PLAYER_MALE_SIDE_WALK_TL:Int;
	var PLAYER_MALE_SIDE_WALK_TR:Int;
	var PLAYER_MALE_SIDE_WALK_BL:Int;
	var PLAYER_MALE_SIDE_WALK_BR:Int;
	
	var PLAYER_MALE_FORWARD_BIKE_TL:Int;
	var PLAYER_MALE_FORWARD_BIKE_TR:Int;
	var PLAYER_MALE_FORWARD_BIKE_BL:Int;
	var PLAYER_MALE_FORWARD_BIKE_BR:Int;
	
	var PLAYER_MALE_BACKWARD_BIKE_TL:Int;
	var PLAYER_MALE_BACKWARD_BIKE_TR:Int;
	var PLAYER_MALE_BACKWARD_BIKE_BL:Int;
	var PLAYER_MALE_BACKWARD_BIKE_BR:Int;
	
	var PLAYER_MALE_SIDE_BIKE_TL:Int;
	var PLAYER_MALE_SIDE_BIKE_TR:Int;
	var PLAYER_MALE_SIDE_BIKE_BL:Int;
	var PLAYER_MALE_SIDE_BIKE_BR:Int;
	
	var PLAYER_MALE_FORWARD_BIKE_SWAY_TL:Int;
	var PLAYER_MALE_FORWARD_BIKE_SWAY_TR:Int;
	var PLAYER_MALE_FORWARD_BIKE_SWAY_BL:Int;
	var PLAYER_MALE_FORWARD_BIKE_SWAY_BR:Int;
	
	var PLAYER_MALE_BACKWARD_BIKE_SWAY_TL:Int;
	var PLAYER_MALE_BACKWARD_BIKE_SWAY_TR:Int;
	var PLAYER_MALE_BACKWARD_BIKE_SWAY_BL:Int;
	var PLAYER_MALE_BACKWARD_BIKE_SWAY_BR:Int;
	
	var PLAYER_MALE_SIDE_BIKE_SWAY_TL:Int;
	var PLAYER_MALE_SIDE_BIKE_SWAY_TR:Int;
	var PLAYER_MALE_SIDE_BIKE_SWAY_BL:Int;
	var PLAYER_MALE_SIDE_BIKE_SWAY_BR:Int;
	
	var NPC_MALE_GAMEBOY_FORWARD_TL:Int;
	var NPC_MALE_GAMEBOY_FORWARD_TR:Int;
	var NPC_MALE_GAMEBOY_FORWARD_BL:Int;
	var NPC_MALE_GAMEBOY_FORWARD_BR:Int;
	
	var NPC_MALE_GAMEBOY_BACKWARD_TL:Int;
	var NPC_MALE_GAMEBOY_BACKWARD_TR:Int;
	var NPC_MALE_GAMEBOY_BACKWARD_BL:Int;
	var NPC_MALE_GAMEBOY_BACKWARD_BR:Int;
	
	var NPC_MALE_GAMEBOY_SIDE_TL:Int;
	var NPC_MALE_GAMEBOY_SIDE_TR:Int;
	var NPC_MALE_GAMEBOY_SIDE_BL:Int;
	var NPC_MALE_GAMEBOY_SIDE_BR:Int;
	
	var RIVAL_FORWARD_TL:Int;
	var RIVAL_FORWARD_TR:Int;
	var RIVAL_FORWARD_BL:Int;
	var RIVAL_FORWARD_BR:Int;
	
	var NUM_SPRITES:Int;
	
	var BANK:Int = 0x30;
}